on:
  push: {}
  pull_request: {}

jobs:
  ubuntu:
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Build CI"
        run: |
          cd $GITHUB_WORKSPACE
          ./ci/build_linux.sh
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
          - os: ubuntu-18.04

  windows:
    runs-on: "${{ matrix.OS }}"
    env:
      VCVARS_PATH: ${{matrix.VCVARS_PATH}}
      BUILDING_SYNTHIZER: "1"
      CI_WINDOWS: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure MSVC Environment Variables
        shell: cmd
        run: |
          call "%VCVARS_PATH%"
          set > %GITHUB_ENV%
      - name: install ninja
        shell: powershell
        run: |
          choco install ninja
      - name: Build C Libraries
        shell: powershell
        run: |
          set-location $Env:GITHUB_WORKSPACE
          ./ci/build_c.ps1
    strategy:
      fail-fast: true
      matrix:
        include:
          - VCVARS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\enterprise\VC\Auxiliary\Build\vcvars32.bat
            OS: windows-2019
          - VCVARS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\enterprise\VC\Auxiliary\Build\vcvars64.bat
            OS: windows-2019
          - VCVARS_PATH: C:\Program Files\Microsoft Visual Studio\2022\enterprise\VC\Auxiliary\Build\vcvars64.bat
            OS: windows-2022

  osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - shell: bash
        run: |
          set -ex
          brew install ninja
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
          ninja test
